Services/Models/MemberShipType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Services.Models
{
    public class MemberShipType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public short SignUpFee { get; set; }
        public byte DurationInMonths { get; set; }
        public byte DiscountRate { get; set; }
    }
}

Services/Models/Requester.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Services.Models
{
    public class Requester
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        public DateTime? BirthDate { get; set; }
        public bool IsSubscribedToNewLetter { get; set; }
        public MemberShipType MemberShipType { get; set; }

        public byte MemberShipTypeId { get; set; }

    }
}

Services/Models/Service.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Services.Models
{
    public class Service
    {
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public int ServiceDuration { get; set; }
        public int ServiceCost { get; set; }
        public bool Active { get; set; }
    }
}

Services/Models/ServicesContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Services.Models
{
    public class ServicesContext : DbContext
    {
        public DbSet<Service> Services { get; set; }

        public DbSet<Requester> Requesters { get; set; }

        public ServicesContext()
            :base("name=DefaultConnection")
        {

        }
    }
}

Services/ViewModels/ServicesViewModels.cs
using Services.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Services.ViewModels
{
    public class ServicesViewModels
    {
        public Service Service { get; set; }
        public List<Requester> Requester { get; set; }

    }
}

Services/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Services.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Services/Controllers/RequesterController.cs
using Services.Models;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Services.Controllers
{
    public class RequesterController : Controller
    {

        private ServicesContext _context;

        public RequesterController()
        {
            _context = new ServicesContext();
        }
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
        // GET:  Requester
        public ActionResult Index()
        {

            var requester = _context.Requesters.Include(c => c.MemberShipType).ToList();

            return View(requester);

        }
        public ActionResult Details(int id)
        {
            var req = _context.Requesters.Include(c=>c.MemberShipType).SingleOrDefault(c => c.Id == id);

            if (req == null)
            {
                return HttpNotFound();
            }
            return View(req);
        }
    }
}

Services/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Services.Models;
using Services.ViewModels;

namespace Services.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Service
        public ActionResult Index()
        {
            var services = GetServices();
            return View(services);

        }
        public ActionResult Details(int id)
        {
            var services = GetServices().SingleOrDefault(c => c.ServiceId == id);

            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }
        private IEnumerable<Service> GetServices()
        {
            var service = new List<Service>()
            {
              new Service{  ServiceId = 1,
                ServiceName = "Passport",
                ServiceDuration = 3,
                ServiceCost = 12,
                Active = true },

               new Service{ ServiceId = 2,
                ServiceName = "Birth",
                ServiceDuration = 3,
                ServiceCost = 12,
                Active = true}
            };
            return service;
        }

        //var requester = new List<Requester>()
        //{
        //    new Requester{Id=1,Name="Owais"},
        //    new Requester{Id=2,Name="Ahmad"}
        //};


        //var ser = new ServicesViewModels()
        //{
        //    Service = service,
        //    Requester = requester
        //};



        //return View(ser);
        //return View(service);
        // return new ViewResult();
        //return new HttpNotFoundResult();
        //return RedirectToAction("index");
    }
}

Services/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Services/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Services/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Services/Views/Requester/Details.cshtml
@model Services.Models.Requester
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Requester Details:<br/> @Model.Name</h2>

<ul>
    <li>MemberShip Type :@Model.MemberShipType.Name</li>
    @if (Model.BirthDate.HasValue)
    {
        <li>Birth Date:@Model.BirthDate</li>
    }


</ul>

Services/Views/Requester/Index.cshtml
@model IEnumerable<Services.Models.Requester>

@*@model Services.ViewModels.ServicesViewModels*@

@{
    ViewBag.Title = "Service";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Requesters</h2>

@if (Model.Count() == 0)
{
    <text>There is no requesters</text>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Requesters</th>
                <th>MemberShip Type</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var req in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(req.Name, "Details", "Requester", new { id = req.Id }, null)
                    </td>
                    <td>
                       @req.MemberShipType.Name
                    </td>
                </tr>
            }
        </tbody>
    </table>




}

Services/Views/Service/Details.cshtml
@model Services.Models.Service
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Service Details: @Model.ServiceName</h2>

Services/Views/Service/Index.cshtml
@model  IEnumerable<Services.Models.Service>
@{
    ViewBag.Title = "Service";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Services</h2>

@if (Model.Count() == 0)
{
    <text>There is no Services</text>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Services</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ser in Model)
            {
                <tr>
                    <td>@Html.ActionLink(ser.ServiceName,"Details","Service",new {id=ser.ServiceId},null)</td>
                </tr>

            }
        </tbody>
    </table>




}

Services/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Services/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("View Services", "Index", "Service")</li>
                <li>@Html.ActionLink("View Requesters", "Index", "Requester")</li>
            </ul>
        </div>
    </div>
</div>